[pytest]
minversion = 7.0
; addopts = -ra
; filterwarnings =
;     error::DeprecationWarning
;     ignore::DeprecationWarning:pybind11.*
testpaths = tests
pythonpath = .
markers =
    cpp: tests that require the compiled C++ extension
    slow: slower integration tests